CREATE TABLE `webinar_funnel_steps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`webinarId` int NOT NULL,
	`stepOrder` int DEFAULT 0,
	`stepType` enum('registration','confirmation','reminder','watch','offer','thankyou') NOT NULL,
	`title` varchar(255),
	`pageBlocksJson` json,
	`emailSubject` varchar(255),
	`emailBody` text,
	`triggerType` enum('immediate','delay','scheduled') DEFAULT 'immediate',
	`triggerDelayMinutes` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	CONSTRAINT `webinar_funnel_steps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webinar_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`webinarId` int NOT NULL,
	`orgId` int NOT NULL,
	`firstName` varchar(128),
	`lastName` varchar(128),
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`customFields` json,
	`registeredAt` timestamp NOT NULL DEFAULT (now()),
	`attended` boolean DEFAULT false,
	`watchedSeconds` int DEFAULT 0,
	`completedAt` timestamp,
	`convertedAt` timestamp,
	`ipAddress` varchar(45),
	CONSTRAINT `webinar_registrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webinar_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`webinarId` int NOT NULL,
	`registrationId` int,
	`sessionToken` varchar(128) NOT NULL,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`lastHeartbeatAt` timestamp DEFAULT (now()),
	`endedAt` timestamp,
	`watchedSeconds` int DEFAULT 0,
	`peakViewerCount` int DEFAULT 0,
	`ipAddress` varchar(45),
	`userAgent` text,
	CONSTRAINT `webinar_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `webinar_sessions_sessionToken_unique` UNIQUE(`sessionToken`)
);
--> statement-breakpoint
CREATE TABLE `webinars` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orgId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`type` enum('live','evergreen') NOT NULL DEFAULT 'evergreen',
	`videoSource` enum('upload','youtube','vimeo','zoom','teams','embed') DEFAULT 'youtube',
	`videoUrl` text,
	`videoFileUrl` text,
	`videoFileKey` text,
	`meetingUrl` text,
	`meetingId` varchar(128),
	`scheduledAt` timestamp,
	`durationMinutes` int DEFAULT 60,
	`timezone` varchar(64) DEFAULT 'America/New_York',
	`replayDelayMinutes` int DEFAULT 0,
	`aiViewersEnabled` boolean DEFAULT false,
	`aiViewersMin` int DEFAULT 50,
	`aiViewersMax` int DEFAULT 300,
	`aiViewersPeakAt` int DEFAULT 30,
	`salesPageBlocksJson` json,
	`thumbnailUrl` text,
	`requireRegistration` boolean DEFAULT true,
	`registrationFormFields` json,
	`postWebinarAction` enum('product','url','thankyou','none') DEFAULT 'none',
	`postWebinarProductId` int,
	`postWebinarUrl` text,
	`postWebinarMessage` text,
	`postWebinarDelaySeconds` int DEFAULT 0,
	`isPublished` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `webinars_id` PRIMARY KEY(`id`)
);
